package pe.lamborgini.domain.mapping;
// Generated 29/06/2011 07:47:21 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
public class Concepto implements java.io.Serializable {

    private Integer idConcepto;
    private String detalleConcepto;
    private Set<PagoHelado> pagoHelados = new HashSet<PagoHelado>(0);

    public Concepto() {
    }

    public Concepto(int idConcepto) {
        this.idConcepto = idConcepto;
    }

    public Concepto(String detalleConcepto) {
        this.detalleConcepto = detalleConcepto;
    }

    public Concepto(String detalleConcepto, Set<PagoHelado> pagoHelados) {
        this.detalleConcepto = detalleConcepto;
        this.pagoHelados = pagoHelados;
    }

    public Integer getIdConcepto() {
        return this.idConcepto;
    }

    public void setIdConcepto(Integer idConcepto) {
        this.idConcepto = idConcepto;
    }

    public String getDetalleConcepto() {
        return detalleConcepto;
    }

    public void setDetalleConcepto(String detalleConcepto) {
        this.detalleConcepto = detalleConcepto;
    }

    public Set<PagoHelado> getPagoHelados() {
        return this.pagoHelados;
    }

    public void setPagoHelados(Set<PagoHelado> pagoHelados) {
        this.pagoHelados = pagoHelados;
    }
}
