package pe.lamborgini.domain.mapping;
// Generated 29/06/2011 07:47:21 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * PagoHelado generated by hbm2java
 */
public class PagoHelado implements java.io.Serializable {

    private Integer idpagoHelado;
    private Factura factura;
    private Concepto concepto;
    private double cantPagada;
    private Set<DetalleHelado> detalleHelados = new HashSet<DetalleHelado>(0);

    public PagoHelado() {
    }

    public PagoHelado(Factura factura, Concepto concepto, int cantPagada) {
        this.factura = factura;
        this.concepto = concepto;
        this.cantPagada = cantPagada;
    }

    public PagoHelado(Factura factura, Concepto concepto, int cantPagada, Set<DetalleHelado> detalleHelados) {
        this.factura = factura;
        this.concepto = concepto;
        this.cantPagada = cantPagada;
        this.detalleHelados = detalleHelados;
    }

    public Integer getIdpagoHelado() {
        return this.idpagoHelado;
    }

    public void setIdpagoHelado(Integer idpagoHelado) {
        this.idpagoHelado = idpagoHelado;
    }

    public Factura getFactura() {
        return this.factura;
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    public Concepto getConcepto() {
        return this.concepto;
    }

    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }

    public double getCantPagada() {
        return this.cantPagada;
    }

    public void setCantPagada(double cantPagada) {
        this.cantPagada = cantPagada;
    }

    public Set<DetalleHelado> getDetalleHelados() {
        return this.detalleHelados;
    }

    public void setDetalleHelados(Set<DetalleHelado> detalleHelados) {
        this.detalleHelados = detalleHelados;
    }
}
