language: java
sudo: false
install: true

addons:
  apt:
    update: true

  sonarcloud:
    organization: "cesardl-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

jdk:
  - oraclejdk8

git:
  #Travis CI uses shallow clone to speed up build times, but a truncated SCM history
  #may cause issues when SonarCloud computes blame data.
  depth: false

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS heladeros CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - mysql -u travis heladeros < database/heladeros.sql

script:
  - mvn clean verify
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sonar-scanner; fi

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/.sonarscanner
