package pe.lamborgini.domain.mapping;
// Generated 29/06/2011 07:47:21 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Helado generated by hbm2java
 */
public class Helado implements java.io.Serializable {

    private Integer idHelado;
    private String nombreHelado;
    private double precio;
    private Set<StockHelado> stockHelados = new HashSet<StockHelado>(0);
    private Set<DetalleHelado> detalleHelados = new HashSet<DetalleHelado>(0);

    public Helado() {
    }

    public Helado(String nombreHelado, double precio) {
        this.nombreHelado = nombreHelado;
        this.precio = precio;
    }

    public Helado(String nombreHelado, double precio, Set<StockHelado> stockHelados, Set<DetalleHelado> detalleHelados) {
        this.nombreHelado = nombreHelado;
        this.precio = precio;
        this.stockHelados = stockHelados;
        this.detalleHelados = detalleHelados;
    }

    public Integer getIdHelado() {
        return this.idHelado;
    }

    public void setIdHelado(Integer idHelado) {
        this.idHelado = idHelado;
    }

    public String getNombreHelado() {
        return this.nombreHelado;
    }

    public void setNombreHelado(String nombreHelado) {
        this.nombreHelado = nombreHelado;
    }

    public double getPrecio() {
        return this.precio;
    }

    public void setPrecio(double precio) {
        this.precio = precio;
    }

    public Set<StockHelado> getStockHelados() {
        return this.stockHelados;
    }

    public void setStockHelados(Set<StockHelado> stockHelados) {
        this.stockHelados = stockHelados;
    }

    public Set<DetalleHelado> getDetalleHelados() {
        return this.detalleHelados;
    }

    public void setDetalleHelados(Set<DetalleHelado> detalleHelados) {
        this.detalleHelados = detalleHelados;
    }
}
