package pe.lamborgini.domain.mapping;
// Generated 29/06/2011 07:47:21 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Helado generated by hbm2java
 *
 * @author Cesardl
 */
public class Helado implements java.io.Serializable {

    private static final long serialVersionUID = 397776243260252512L;

    private Integer idHelado;
    private String nombreHelado;
    private double precio;
    private StockHelado stockHelado;
    private Set<DetalleHelado> detalleHelados = new HashSet<>(0);

    public Helado() {
    }

    public Helado(String nombreHelado, double precio) {
        this.nombreHelado = nombreHelado;
        this.precio = precio;
    }

    public Helado(String nombreHelado, double precio, StockHelado stockHelado, Set<DetalleHelado> detalleHelados) {
        this.nombreHelado = nombreHelado;
        this.precio = precio;
        this.stockHelado = stockHelado;
        this.detalleHelados = detalleHelados;
    }

    public Integer getIdHelado() {
        return this.idHelado;
    }

    public void setIdHelado(Integer idHelado) {
        this.idHelado = idHelado;
    }

    public String getNombreHelado() {
        return this.nombreHelado;
    }

    public void setNombreHelado(String nombreHelado) {
        this.nombreHelado = nombreHelado;
    }

    public double getPrecio() {
        return this.precio;
    }

    public void setPrecio(double precio) {
        this.precio = precio;
    }

    public StockHelado getStockHelado() {
        return stockHelado;
    }

    public void setStockHelado(StockHelado stockHelado) {
        this.stockHelado = stockHelado;
    }

    public Set<DetalleHelado> getDetalleHelados() {
        return this.detalleHelados;
    }

    public void setDetalleHelados(Set<DetalleHelado> detalleHelados) {
        this.detalleHelados = detalleHelados;
    }
}
