package pe.lamborgini.domain.mapping;
// Generated 29/06/2011 07:47:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
public class Concepto  implements java.io.Serializable {


     private Integer idConcepto;
     private int numeroConcepto;
     private int porcentaje;
     private Set<PagoHelado> pagoHelados = new HashSet<PagoHelado>(0);

    public Concepto() {
    }

	
    public Concepto(int numeroConcepto, int porcentaje) {
        this.numeroConcepto = numeroConcepto;
        this.porcentaje = porcentaje;
    }
    public Concepto(int numeroConcepto, int porcentaje, Set<PagoHelado> pagoHelados) {
       this.numeroConcepto = numeroConcepto;
       this.porcentaje = porcentaje;
       this.pagoHelados = pagoHelados;
    }
   
    public Integer getIdConcepto() {
        return this.idConcepto;
    }
    
    public void setIdConcepto(Integer idConcepto) {
        this.idConcepto = idConcepto;
    }
    public int getNumeroConcepto() {
        return this.numeroConcepto;
    }
    
    public void setNumeroConcepto(int numeroConcepto) {
        this.numeroConcepto = numeroConcepto;
    }
    public int getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(int porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Set<PagoHelado> getPagoHelados() {
        return this.pagoHelados;
    }
    
    public void setPagoHelados(Set<PagoHelado> pagoHelados) {
        this.pagoHelados = pagoHelados;
    }




}


