package pe.lamborgini.domain.mapping;
// Generated 29/06/2011 07:47:21 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Heladero generated by hbm2java
 */
public class Heladero implements java.io.Serializable {

    private Integer idHeladero;
    private Concesionario concesionario;
    private String nombres;
    private String apellidos;
    private Set<ContratoHeladero> contratoHeladeros = new HashSet<ContratoHeladero>(0);
    private Set<HeladosEntregadoRecibido> heladosEntregadoRecibidos = new HashSet<HeladosEntregadoRecibido>(0);

    public Heladero() {
    }

    public Heladero(int idHeladero) {
        this.idHeladero = idHeladero;
    }

    public Heladero(Concesionario concesionario, String nombres, String apellidos) {
        this.concesionario = concesionario;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }

    public Heladero(Concesionario concesionario, String nombres, String apellidos, Set<ContratoHeladero> contratoHeladeros, Set<HeladosEntregadoRecibido> heladosEntregadoRecibidos) {
        this.concesionario = concesionario;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.contratoHeladeros = contratoHeladeros;
        this.heladosEntregadoRecibidos = heladosEntregadoRecibidos;
    }

    public Integer getIdHeladero() {
        return this.idHeladero;
    }

    public void setIdHeladero(Integer idHeladero) {
        this.idHeladero = idHeladero;
    }

    public Concesionario getConcesionario() {
        return this.concesionario;
    }

    public void setConcesionario(Concesionario concesionario) {
        this.concesionario = concesionario;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public Set<ContratoHeladero> getContratoHeladeros() {
        return this.contratoHeladeros;
    }

    public void setContratoHeladeros(Set<ContratoHeladero> contratoHeladeros) {
        this.contratoHeladeros = contratoHeladeros;
    }

    public Set<HeladosEntregadoRecibido> getHeladosEntregadoRecibidos() {
        return this.heladosEntregadoRecibidos;
    }

    public void setHeladosEntregadoRecibidos(Set<HeladosEntregadoRecibido> heladosEntregadoRecibidos) {
        this.heladosEntregadoRecibidos = heladosEntregadoRecibidos;
    }
}
